# Generated by Django 3.1 on 2020-10-04 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('head_0', models.CharField(max_length=200)),
                ('head_1', models.CharField(max_length=500)),
                ('head_2', models.CharField(max_length=500)),
            ],
        ),
    ]
