# Generated by Django 3.1 on 2020-08-23 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20200818_0044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.IntegerField(max_length=12)),
                ('email', models.CharField(max_length=100)),
                ('query', models.CharField(max_length=500)),
            ],
        ),
    ]
